FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg/mod true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/admin-rest ./cmd/admin-rest

FROM alpine:3.19
WORKDIR /app
COPY --from=build /out/admin-rest ./admin-rest
EXPOSE 8083
ENTRYPOINT ["./admin-rest"]
