name: runner-qwen CI

on:
  push:
    paths:
      - 'runner-qwen/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'runner-qwen/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runner-qwen
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run tests
        run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: runner-qwen
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: runner-qwen
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/runner-qwen:latest
